function [filename, filecode] = read(index, location, batchname)

    % READ parses a filename file and a filecode file (generated by BATCHIFY)
    % and returns a filename as a character array and a filecode pair as a 1x2 vector
    % This is particularly useful in a batch function.
    %
    %   [filenames, filecodes] = RatCatcher.READ(location, batchname, index)
    %
    % See also RATCATCHER, RATCATCHER.BATCHIFY

    % load the entire filename file
    % this is slow, but MATLAB has clunky textread options
    try
        filename    = filelib.read(fullfile(location, ['filenames-', batchname, '.txt']));
    catch
        error(['File not found at: ' fullfile(location, ['filenames-', batchname, '.txt'])])
    end
    % acquire only the character vector corresponding to the indexed filename
    filename    = filename{index};
    % acquire the cell number using similarly clunky indexing
    filecode    = csvread(fullfile(location, ['filecodes-', batchname, '.csv']), index-1, 0, [index-1, 0, index-1, 1]);

end % function
