function [filename, cellnum] = read(location, batchname, index)

    % READ parses a filename file and a cellnum file (generated by BATCHIFY)
    % and returns a filename as a character array and a cellnum pair as a 1x2 vector
    % This is particularly useful in a batch function.
    %
    %   [filenames, cellnum] = RatCatcher.READ(location, batchname, index)
    %
    % See also RATCATCHER, RATCATCHER.BATCHIFY

    % load the entire filename file
    % this is slow, but MATLAB has clunky textread options
    filename    = lineRead([location filesep 'filenames-' batchname '.txt']);
    % acquire only the character vector corresponding to the indexed filename
    filename    = filename{index};
    % acquire the cell number using similarly clunky indexing
    cellnum     = csvread([location filesep 'cellnums-' batchname '.csv'], index-1, 0, [index-1, 0, index-1, 1]);

end % function
